<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>13</LangVersion>
        <Nullable>warnings</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Aseprite\Aseprite.csproj">
            <Project>{13c6f252-0b3c-4a22-a9db-270c76657fab}</Project>
            <Name>Aseprite</Name>
        </ProjectReference>
        <ProjectReference Include="..\VelcroPhysics\VelcroPhysics.MonoGame.csproj">
            <Project>{4650bd15-4b03-4a7e-98d4-9f8697ed2eb4}</Project>
            <Name>VelcroPhysics.MonoGame</Name>
        </ProjectReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="ImGui.NET" Version="1.89.9.3"/>
        <PackageReference Include="MonoGame.Extended" Version="4.0.4"/>
        <PackageReference Include="MonoGame.Framework.Content.Pipeline" Version="3.8.*">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.*">
            <PrivateAssets>All</PrivateAssets>
        </PackageReference>
    </ItemGroup>
</Project>